/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.codegen;


import ru.tinkoff.edu.java.scrapper.domain.jooq.codegen.tables.Client;
import ru.tinkoff.edu.java.scrapper.domain.jooq.codegen.tables.Link;
import ru.tinkoff.edu.java.scrapper.domain.jooq.codegen.tables.UserLinks;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CLIENT</code>.
     */
    public static final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>USER_LINKS</code>.
     */
    public static final UserLinks USER_LINKS = UserLinks.USER_LINKS;
}
