scrapper:
  test: hi
  scheduler:
  interval: 5000
  exchange: "message"
  queue: "message.queue"

springdoc:
  swagger-ui:
    path: "/swagger-ui"

client:
  base-url:
    github: "https://api.github.com"
    stackoverflow: "https://api.stackexchange.com/2.3"

spring:
  liquibase:
    enabled: false
  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driverClassName: org.postgresql.Driver


  database-access-type: jpa